on:
  push:
    branches:
      - campus_certificaciones
name: 🚀 Deploy campus_certificaciones branch to certificaciones.uvirtual.org
jobs:
  web-deploy:
    name: 🎉 Deploy to certificaciones.uvirtual.org
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER_CERTIFICACION}}
          username: ${{ secrets.USER_CERTIFICACION}}
          password: ${{ secrets.PASS_CERTIFICACION}}
          server-dir: /public_html/local/uvirtual/
