on:
  push:
    branches:
      - main
name: 🚀 Deploy main branch to campus.uvirtual.org
jobs:
  web-deploy:
    name: 🎉 Deploy to campus
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER_PROD}}
          username: ${{ secrets.USER_PROD}}
          password: ${{ secrets.PASS_PROD}}
          server-dir: /public_html/local/
